### ISSUE TITLE
Steam login not working

### ISSUE THREAD

**Issue by miklund** [rubriks/r3pl4y#3]
Started GET "/users/auth/steam" for 192.168.0.14 at 2015-12-05 08:06:39 +0000
Started GET "/users/auth/steam/callback?_method=post&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198030991346&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198030991346&openid.return_to=http%3A%2F%2Freplay.mikaellundin.name%2Fusers%2Fauth%2Fsteam%2Fcallback%3F_method%3Dpost&openid.response_nonce=2015-12-05T08%3A06%3A48ZyhF%2FZH%2F%2F0zL83Eoezp3ietNm96w%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=DjquBTpTe3O1glvL%2F7Js4q8QSwA%3D" for 192.168.0.14 at 2015-12-05 08:06:48 +0000

MultiJson::DecodeError (795: unexpected token at '<html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>'):
  json (1.7.6) lib/json/common.rb:155:in `parse'
  json (1.7.6) lib/json/common.rb:155:in`parse'
  multi_json (1.5.0) lib/multi_json/adapters/json_common.rb:7:in `load'
  multi_json (1.5.0) lib/multi_json.rb:96:in`load'
  omniauth-steam (1.0.0) lib/omniauth/strategies/steam.rb:31:in `raw_info'
  omniauth-steam (1.0.0) lib/omniauth/strategies/steam.rb:35:in`player'
  omniauth-steam (1.0.0) lib/omniauth/strategies/steam.rb:14:in `block in <class:Steam>'
  omniauth (1.1.0) lib/omniauth/strategy.rb:102:in`instance_eval'
  omniauth (1.1.0) lib/omniauth/strategy.rb:102:in `block in compile_stack'
  omniauth (1.1.0) lib/omniauth/strategy.rb:101:in`each'
  omniauth (1.1.0) lib/omniauth/strategy.rb:101:in `inject'
  omniauth (1.1.0) lib/omniauth/strategy.rb:101:in`compile_stack'
  (eval):7:in `info_stack'
  omniauth (1.1.0) lib/omniauth/strategy.rb:313:in`info'
  omniauth (1.1.0) lib/omniauth/strategy.rb:326:in `auth_hash'
  omniauth (1.1.0) lib/omniauth/strategy.rb:353:in`callback_phase'
  omniauth-openid (1.0.1) lib/omniauth/strategies/open_id.rb:81:in `callback_phase'
  omniauth (1.1.0) lib/omniauth/strategy.rb:219:in`callback_call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:175:in `call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in`call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:177:in `call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in`call'
  omniauth (1.1.0) lib/omniauth/strategy.rb:177:in `call!'
  omniauth (1.1.0) lib/omniauth/strategy.rb:157:in`call'
  warden (1.2.1) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in`catch'
  warden (1.2.1) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.3) lib/rack/etag.rb:23:in `call'
  rack (1.4.3) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.3) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.3) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`_run__266819007__call__413890121__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.3) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.3) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in
`call'
  rack (1.4.3) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in`call'
  railties (3.2.11) lib/rails/engine.rb:479:in `call'
  railties (3.2.11) lib/rails/application.rb:223:in`call'
  rack (1.4.3) lib/rack/content_length.rb:14:in `call'
  railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.3) lib/rack/handler/webrick.rb:59:in `service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /usr/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

**Comment by rubriks** [comment]
Fixed. This was due to wrong access key in ENV variable.
